# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liberty-jax-ws-sample
  labels:
    app: liberty-jax-ws-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liberty-jax-ws-sample
  template:
    metadata:
      labels:
        app: liberty-jax-ws-samplea
    spec:
      containers:
      - name: liberty-jax-ws-sample
        image: <REGISTRY>/<NAMESPACE>/myapp:v1.0.0
        ports:
        - containerPort: 9080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true


